FROM nginx:1.13.8-alpine

#In kubernetes, this value must be the same with, php service name
ARG PHP_UPSTREAM_CONTAINER=um-api-php
ARG PHP_UPSTREAM_PORT=9000

RUN apk update \
    && apk upgrade \
    && apk add --no-cache bash \
    && adduser -D -H -u 1000 -s /bin/bash www-data

# Set upstream conf and remove the default conf
RUN echo "upstream php-upstream { server ${PHP_UPSTREAM_CONTAINER}:${PHP_UPSTREAM_PORT}; }" > /etc/nginx/conf.d/upstream.conf \
    && rm /etc/nginx/conf.d/default.conf

COPY ./app-configs/nginx/nginx.conf /etc/nginx/
COPY ./app-configs/nginx/default.conf /etc/nginx/sites-available/

CMD ["nginx", "-g", "daemon off;"]

EXPOSE 80 443
